FROM ubuntu:latest

RUN apt-get update \
&& apt-get install -y python3-pip python3-dev vim git


RUN git clone https://github.com/pereira-tony/td1-nosql-m1-web.git /workspace
WORKDIR /workspace


RUN pip3 install jupyter \
&& pip3 install notebook \
&& pip3 install pandas \
&& pip3 install numpy

CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]





